### ISSUE TITLE
Memory Leak Due to objc_associated References

### ISSUE THREAD

**Issue by patgoley** [nodekit-io/nodekit-darwin-lite#8]
I'm currently having an issue where the NKJSContext, loaded plugins, and NKScriptSource objects will not deallocate when attempting to dispose of them (i.e. `self.context.stop() ; self.context = nil`). The references appear to originate from the use of `objc_setAssociatedObject` when loading plugins and other script sources. I'm not sure I understand why associated objects are being used over normal retaining references, such as storing the objects in a dictionary on the context, but maybe there's something I'm missing. As the objects are currently retained using their pointer address as the key, it's difficult to find and unregister them all on `stop`. Each plugin passed into NKScripting must also remember to unregister their NKScriptObject from their own associated objects. 

Associated objects are also difficult to track in the memory graph debugger in Xcode. We should stick to using known properties that exist at compile time for better tracability. Let me know any thoughts on these updates and if all looks good I can execute the fix. Thanks!

**Comment by guycreate** [comment]
Definitely no issue with fixes that improve this.  

As I recall, the use obj_setAssociatedObject was intended to prevent memory leaks due to circular references -- contexts that reference plugins that in turn reference data items in the context that prevented garbage handling forever, but it seems odd looking at it now to see it on the SELF vs something passed in as I agree a dictionary should be able to cover it.

The native<-->JS interface at that time (Swift 2 not even 2.3!) was particularly unforgiving in making memory attachments across the boundary and so the simplest method at the time seemed to be manual tracking the references carefully, in other words objc_setAssociatedObject, although again in these libraries this was typically done to objects other than self.   

Since this is now proving to introduce a memory leak then we should definitely change that.     The disposal .stop() were added later I think so its entirely possible we did not foresee all the necessary cleanup, but regardless, yes please do execute the fix.  I don't foresee problems with a dictionary in looking at the code today.   Worth testing and watching for the memory cleanup specifically though after the fix is executed to make sure we are not retaining the entire JS execution context unnecessarily after a stop().

**Comment by patgoley** [comment]
Hey Guy, I've done some more testing here and everything looks solid as far as I can tell. I know you are on vacation so in the interest of time, I'm going to go ahead and merge here. We can create another patch release once you've had a chance to review if necessary.

Worth noting that I fixed all of the major compiler warnings, which is good as they do appear in host project builds. Also did some minor formatting clean up for consistency and made sure all of the new files had the appropriate copyright header comments. Let me know if you think I've missed something. Thanks!
